# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7270f1c0fae41fcb91abb27af1c77082450b72a605755aec39118d2ffcdfe076689fa2611e1f39ce59534f8af5b4391bc35d616b4a0040bc0b39cefe28d3602

test:
  secret_key_base: 814fec491b6003d1bc446ca4b5852b70211ad415714eee9f90c1ec1fc5fcafa294a72f30ae6cc79636f67e02d67792c3a44f2cf9a9c8f35dba4a75b7e3c07d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
